### PR TITLE
ofp: extract Super imgs & ops: add docopt requirement

### PR DESCRIPTION
**Pull request by MlgmXyysd**
Fix https://github.com/bkerler/oppo_decrypt/issues/31

image

Tested on OnePlus 9 Pro LE2120domestic_11_A.06_2021042500040000.ofp

In addition, does anyone know how to correctly convert OFP to OPS?

image

### CODE REVIEW

**Comment by MlgmXyysd** [comment]
@bkerler

**Comment by bkerler** [comment]
Thanks ;)

**Comment by zacharee** [comment]
What do we do with these super image parts? I've tried combining them with dd, which doesn't work.

**Comment by MlgmXyysd** [comment]
> What do we do with these super image parts? I've tried combining them with dd, which doesn't work.

I'm not sure that after using lpunpack for one of the super splits, some images are empty (the content is all 0x00 or the size is 0), and the images with content in other super splits can just make up for these empty images.
We may need to make it up and reuse lpmake packaging. 

@bkerler Do you have any ideas?

**Comment by rokibhasansagar** [comment]
> > What do we do with these super image parts? I've tried combining them with dd, which doesn't work.
> 
> I'm not sure that after using lpunpack for one of the super splits, some images are empty (the content is all 0x00 or the size is 0), and the images with content in other super splits can just make up for these empty images.
> We may need to make it up and reuse lpmake packaging.
> 

Can you try to convert those sparse images to one raw image?

`simg2img <split-super-images-serially-put> super.img.raw`

From the NVList (in the image you provided), try any variant of 3 image
Like `simg2img super.0.9fxxx super.1.bdxxx super.2.47xxx super.img.raw`

I forgot where, but tried something like this around a month ago for a firmware dump 🤔

**Comment by zacharee** [comment]
In my case, there are over 10 super partials. I'll try simg2img when I get the chance.

**Comment by MlgmXyysd** [comment]
> > > What do we do with these super image parts? I've tried combining them with dd, which doesn't work.
> > 
> > 
> > I'm not sure that after using lpunpack for one of the super splits, some images are empty (the content is all 0x00 or the size is 0), and the images with content in other super splits can just make up for these empty images.
> > We may need to make it up and reuse lpmake packaging.
> 
> Can you try to convert those sparse images to one raw image?
> 
> `simg2img <split-super-images-serially-put> super.img.raw`
> 
> From the NVList (in the image you provided), try any variant of 3 image
> Like `simg2img super.0.9fxxx super.1.bdxxx super.2.47xxx super.img.raw`
> 
> I forgot where, but tried something like this around a month ago for a firmware dump 🤔

Wow, I never knew that simg2img can merge multiple split files. This command generates a 10G img.

**Comment by zacharee** [comment]
I tried specifying the images in the order shown in `super.xml`, and it just returned:

```
Invalid sparse file format at header magic
Failed to read sparse file
```

Putting them in alphabetical order returns the same error.

**Comment by zacharee** [comment]
Oh, I misunderstood how they go together. I'm re-extracting now and will try the 3 images specified in one of the configurations in the NVList.

**Pull request merged**
